#!/usr/bin/env bash
# Step 4: persist everything across reboots.
#   - touch calibration  -> /etc/udev/hwdb.d/ (udev hwdb, applied by libinput)
#   - rotation + scale   -> ~/.config/labwc/autostart (wlr-randr at session start)
# Usage:
#   sudo steps/04-persist.sh                 # uses calibration.env if present, else defaults.env
#   sudo steps/04-persist.sh --use-defaults  # ignore calibration.env
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"
# shellcheck source=../defaults.env
source "$SCRIPT_DIR/../defaults.env"

require_root

# Resolve the desktop user before changing anything.
user="$(desktop_user)"
group="$(id -gn "$user")"
home_dir="$(getent passwd "$user" | cut -d: -f6)"
[ -n "$home_dir" ] || die "Could not resolve home directory for user '$user'"

# Rotation precedence: override from *-show / rotate.sh (environment), then the
# value saved by an earlier *-show run, then defaults.env.
if [ -n "${OUTPUT_TRANSFORM_OVERRIDE:-}" ]; then
  OUTPUT_TRANSFORM="$OUTPUT_TRANSFORM_OVERRIDE"
elif [ -s "$TRANSFORM_STATE" ]; then
  OUTPUT_TRANSFORM="$(cat "$TRANSFORM_STATE")"
  log "Using saved rotation (transform $OUTPUT_TRANSFORM) from $TRANSFORM_STATE"
fi
# wlr-randr takes "normal" for no rotation; "0" is rejected.
case "$OUTPUT_TRANSFORM" in
  0|normal) OUTPUT_TRANSFORM=normal ;;
  90|180|270) ;;
  *) die "Invalid OUTPUT_TRANSFORM '$OUTPUT_TRANSFORM' (use 0, 90, 180 or 270)" ;;
esac
if [ -n "${OUTPUT_TRANSFORM_OVERRIDE:-}" ]; then
  mkdir -p "$(dirname "$TRANSFORM_STATE")"
  echo "$OUTPUT_TRANSFORM" > "$TRANSFORM_STATE"
fi

if [ "${1:-}" != "--use-defaults" ] && [ -f "$SCRIPT_DIR/../calibration.env" ]; then
  # shellcheck source=/dev/null
  source "$SCRIPT_DIR/../calibration.env"
  log "Using measured calibration from calibration.env"
else
  log "Using default calibration matrix from defaults.env"
fi

## --- Touch calibration via udev hwdb -------------------------------------
match="$(touch_hwdb_match)"
touch_name="$(touch_device_name)"
[ -n "$match" ] && [ -n "$touch_name" ] \
  || die "ADS7846 touch controller not present — run steps/02-verify-boot.sh first."
log "hwdb match: $match"

backup_file "$HWDB_FILE"
cat > "$HWDB_FILE" <<EOF
# SPI LCD resistive touch calibration (generated by pi5-ili9486-touchscreen).
# The leading space on the property line is required hwdb syntax.
$match
 LIBINPUT_CALIBRATION_MATRIX=$CAL_MATRIX
EOF
systemd-hwdb update
udevadm trigger
log "Calibration persisted to $HWDB_FILE (applies at next login)"

## --- Rotation + scale via labwc autostart --------------------------------
autostart="$home_dir/.config/labwc/autostart"

mkdir -p "$(dirname "$autostart")"
backup_file "$autostart"
mode_arg=""
[ -n "${OUTPUT_MODE:-}" ] && mode_arg="--custom-mode $OUTPUT_MODE "
block="$AUTOSTART_BEGIN
wlr-randr --output $OUTPUT_NAME ${mode_arg}--transform $OUTPUT_TRANSFORM --scale $OUTPUT_SCALE &
$AUTOSTART_END"
write_block "$autostart" "$AUTOSTART_BEGIN" "$AUTOSTART_END" "$block"
log "Mode/rotation/scale persisted to $autostart (runs at labwc session start)"

## --- Touch -> panel output mapping via labwc rc.xml -----------------------
# Without this, labwc maps the touchscreen across the whole desktop when an
# HDMI monitor is also connected.
rcxml="$home_dir/.config/labwc/rc.xml"
if [ ! -f "$rcxml" ]; then
  # Start from the system config so its settings are kept.
  if [ -f /etc/xdg/labwc/rc.xml ]; then
    cp /etc/xdg/labwc/rc.xml "$rcxml"
  else
    printf '<?xml version="1.0"?>\n<labwc_config>\n</labwc_config>\n' > "$rcxml"
  fi
fi
if ! grep -q '</labwc_config>' "$rcxml"; then
  warn "No </labwc_config> in $rcxml — touch not mapped to $OUTPUT_NAME. Add manually:"
  warn "  <touch deviceName=\"$touch_name\" mapToOutput=\"$OUTPUT_NAME\" />"
else
  backup_file "$rcxml"
  remove_block "$rcxml" "$RCXML_BEGIN" "$RCXML_END"
  if grep -q '<touch ' "$rcxml"; then
    warn "$rcxml already has a <touch> entry; check it does not conflict with ours."
  fi
  end_line="$(grep -n '</labwc_config>' "$rcxml" | tail -1 | cut -d: -f1)"
  tmp="$(mktemp)"
  BLOCK="$RCXML_BEGIN
  <touch deviceName=\"$touch_name\" mapToOutput=\"$OUTPUT_NAME\" />
$RCXML_END" awk -v n="$end_line" 'NR == n { print ENVIRON["BLOCK"] } { print }' "$rcxml" > "$tmp"
  cat "$tmp" > "$rcxml"; rm -f "$tmp"
  log "Touch mapped to $OUTPUT_NAME in $rcxml"
fi
chown -R "$user:$group" "$home_dir/.config/labwc"

## --- Verify ---------------------------------------------------------------
echo
if libinput list-devices 2>/dev/null | grep -A20 'ADS7846' | grep -q 'Calibration:.*[0-9]'; then
  log "libinput reports an active calibration matrix:"
  libinput list-devices | grep -A20 'ADS7846' | grep 'Calibration:' | sed 's/^/      /'
else
  warn "Could not confirm calibration via 'libinput list-devices' — check manually."
fi
log "Done. Log out/in (or reboot) for calibration, mode, rotation and scale to apply."
log "Note: 'libinput debug-events' prints raw (pre-calibration) coordinates —"
log "'libinput list-devices' shows the active matrix."
